apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flexstack
  namespace: {{.Values.namespace}}
  labels:
    app: flexstack
spec:
  serviceName: flexstack
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: flexstack
  template:
    metadata:
      labels:
        app: flexstack
      annotations:
        k8s.v1.cni.cncf.io/networks: veth-conf
    spec:
      containers:
        - name: flexstack
          image: {{ .Values.flexstack_deployment.repository }}{{ .Values.flexstack_deployment.tag }}
          imagePullPolicy: {{.Values.pullPolicy}}
          env:
            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/bin/sh", "-c"]
          args:
            - >
              ID=$(echo $POD_INDEX | grep -o '[0-9]*');
              MAC=$(printf '00:00:00:00:00:%02X' $ID);
              exec python app.py --station-id $ID --mac-address $MAC --interface net1
      restartPolicy: {{.Values.restartPolicy}}
---
apiVersion: v1
kind: Service
metadata:
  name: flexstack-prometheus-nodeport
  namespace: v2x
  labels:
    app: flexstack
spec:
  selector:
    app.kubernetes.io/instance: flexstack-kube-prometheus-prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/managed-by: prometheus-operator
  ports:
  - name: http-web
    port: 9090
    nodePort: {{ .Values.prometheus_service.prometheus_node_http_port }}
    protocol: TCP
    targetPort: 9090
  - appProtocol: http
    name: reloader-web
    nodePort: {{ .Values.prometheus_service.prometheus_node_reloder_web_port }}
    port: 8080
    protocol: TCP
    targetPort: reloader-web
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: flexstack-grafana-nodeport
  namespace: v2x
  labels:
    app: flexstack
spec:
  selector:
    app.kubernetes.io/instance: flexstack
    app.kubernetes.io/name: grafana
  ports:
  - name: http-web
    port: 3000
    nodePort: {{ .Values.grafana_service.grafana_node_http_port }}
    protocol: TCP
    targetPort: 3000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: flexstack-prometheus-exporter
  namespace: v2x
  labels:
    app: flexstack
    type: flexstack-prometheus-exporter
spec:
  selector:
    app: flexstack
  ports:
  - name: "metrics"
    port: 8000
    protocol: TCP
    targetPort: 8000

