version: '3.8'

services:
  flexstack1:
    build: .
    container_name: v2xflex_app
    volumes:
      - .:/app
    working_dir: /app
    command: ["--station-id", "1", "--mac-address", "aa:bb:cc:11:22:31"]
    networks:
      - v2xnet
  flexstack2:
    build: .
    container_name: v2xflex_app_2
    volumes:
      - .:/app
    working_dir: /app
    command: ["--station-id", "2", "--mac-address", "aa:bb:cc:11:22:32"]
    networks:
      - v2xnet
networks:
  v2xnet: